services:
  geth:
    image: geth-local:latest
    container_name: geth-node
    ports:
      - "8545:8545"
    command:
      - --dev
      - --dev.period=12
      - --datadir=/root/.ethereum
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --http.api=eth,net,web3,personal,debug
      - --allow-insecure-unlock
      - --verbosity=4
    volumes:
      - geth-data:/root/.ethereum
    restart: unless-stopped
    mem_limit: 1g 
    cpus: 1

volumes:
  geth-data:
